sudo: required
services:
    - docker
before_install:
    - docker build -t vivek170161/react-test -f ./client/Dockerfile.dev ./client
script:
    - docker run -e CI=true vivek170161/react-test npm test -- --coverage
after_success:
    - docker build -t vivek170161/multi-client ./client
    - docker build -t vivek170161/multi-nginx ./nginx
    - docker build -t vivek170161/multi-server ./server
    - docker build -t vivek170161/multi-worker ./worker
# Login to the docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
# Take those images and push them to docker hub
    - docker push vivek170161/multi-client
    - docker push vivek170161/multi-nginx
    - docker push vivek170161/multi-server
    - docker push vivek170161/multi-worker

# Deploy the application to AWS Elastic Beanstalk
deploy:
    provider: elasticbeanstalk
    region: ap-south-1
    app: multi-docker
    env: MultiDocker-env
    bucket_name: elasticbeanstalk-ap-south-1-082872762842
    bucket_path: multi-docker
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    

